src/Study2gether/Study2gether/Areas/Admin/Controllers/AdminAxisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Study2gether.Models;

namespace Study2gether.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminAxisController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminAxisController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Axis
        public async Task<IActionResult> Index()
        {
            return View(await _context.Axis.ToListAsync());
        }

        // GET: Axis/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var axis = await _context.Axis
                .Include(o => o.Posts)
                .FirstOrDefaultAsync(m => m.idAxis == id);
            if (axis == null)
            {
                return NotFound();
            }

            return View(axis);
        }

        // GET: Axis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Axis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("idAxis,name")] Axis axis)
        {
            if (ModelState.IsValid)
            {
                axis.idAxis = Guid.NewGuid();
                _context.Add(axis);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(axis);
        }

        // GET: Axis/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var axis = await _context.Axis.FindAsync(id);
            if (axis == null)
            {
                return NotFound();
            }
            return View(axis);
        }

        // POST: Axis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("idAxis,name")] Axis axis)
        {
            if (id != axis.idAxis)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(axis);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AxisExists(axis.idAxis))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(axis);
        }

        // GET: Axis/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var axis = await _context.Axis
                .FirstOrDefaultAsync(m => m.idAxis == id);
            if (axis == null)
            {
                return NotFound();
            }

            return View(axis);
        }

        // POST: Axis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var axis = await _context.Axis.FindAsync(id);
            _context.Axis.Remove(axis);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AxisExists(Guid id)
        {
            return _context.Axis.Any(e => e.idAxis == id);
        }
    }
}

src/Study2gether/Study2gether/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Study2gether.Models;
using System.Web;
using Microsoft.AspNetCore.Http;
using System.Text.RegularExpressions;
using SendGrid;
using SendGrid.Helpers.Mail;
using DotNetEnv;

namespace Study2gether.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Login([Bind("email,password")] User userForm)
        {
            var userDb = await _context.Users
                .FirstOrDefaultAsync(m => m.email == userForm.email);

            if (userDb == null)
            {
                ViewBag.Message = "Usuário e/ou Senha inválidos!";
                return View();
            }

            bool ispasswordOk = BCrypt.Net.BCrypt.Verify(userForm.password, userDb.password);

            if (ispasswordOk)
            {
                var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, userDb.name == null ? userDb.email : userDb.name),
                        new Claim(ClaimTypes.Thumbprint, userDb.imageLink ),
                        new Claim(ClaimTypes.NameIdentifier, userDb.name == null ? userDb.email : userDb.name),
                        new Claim(ClaimTypes.Role, userDb.isAdmin ? "admin" : "user"),
                        new Claim("idUser", userDb.idUser.ToString()),
                        new Claim("imageLink", userDb.imageLink.ToString()),
                    };

                var userIdentity = new ClaimsIdentity(claims, "login");

                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

                var props = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    ExpiresUtc = DateTime.Now.ToLocalTime().AddDays(7),
                    IsPersistent = true
                };

                await HttpContext.SignInAsync(principal, props);

                return Redirect("/");

            }

            ViewBag.Message = "Usuário e/ou Senha inválidos!";
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cadastro([Bind("idUser,email,password,createdDate")] User user)
        {
            var validateEmail = user.email.EndsWith("@sga.pucminas.br");
            var checkExistingEmail = _context.Users.FirstOrDefault(stored => stored.email == user.email);
            var validatePasswordLength = user.password.Length >= 8;
            if (!validateEmail)
            {
                ModelState.AddModelError("email", "O e-mail deve ser um endereço de e-mail da PUC Minas.");
            }

            if (checkExistingEmail != null)
            {
                ModelState.AddModelError("email", "Este e-mail já está em uso. Por favor, use outro e-mail.");
            }

            if (!validatePasswordLength)
            {
                ModelState.AddModelError("password", "A senha deve ter pelo menos 8 caracteres.");
            }
            if (ModelState.IsValid)
            {
                TempData["success"] = "Sua conta foi criada com sucesso!";
                user.password = BCrypt.Net.BCrypt.HashPassword(user.password);
                user.idUser = Guid.NewGuid();
                user.name = user.email;
                user.imageLink = "https://cdn-icons-png.flaticon.com/512/6596/6596121.png";
                user.createdDate = DateTime.Now;
                _context.Add(user);
                await _context.SaveChangesAsync();
                return View();
            }
            return View(user);
        }

        private bool UserExists(Guid id)
        {
            return _context.Users.Any(e => e.idUser == id);
        }

        public async Task<IActionResult> Historico()
        {   
            var user = await _context.Users
                .Include(p => p.Posts)
                .Include(a => a.Answers)
                .Include(r => r.Reactions)
                .ThenInclude(r => r.Post)
                .FirstOrDefaultAsync(user => user.idUser == Guid.Parse(User.FindFirstValue("idUser")));

            return View("Historico", user);
        }

        public async Task<IActionResult> EditarPerfil()
        {
            var user = await _context.Users
                .FirstOrDefaultAsync(user => user.idUser == Guid.Parse(User.FindFirstValue("idUser")));

            return View("EditarPerfil", user);
        }

        [HttpPost]
        public async Task<IActionResult> EditarPerfil(string name, string description, string imageLink, string socialMedia)
        {
            var user = await _context.Users
                .FirstOrDefaultAsync(user => user.idUser == Guid.Parse(User.FindFirstValue("idUser")));

            if (user != null)
            {
                if (!string.IsNullOrEmpty(name))
                    user.name = name;

                user.description = description;
                user.socialMedia = socialMedia;

                if (!string.IsNullOrEmpty(imageLink))
                { 
                    user.imageLink = imageLink;
                }

                await _context.SaveChangesAsync();
            }
            else
            {
                ViewBag.Message = "Usuário não encontrado.";
                return View();
            }

            return RedirectToAction("Historico");
        }

        public async Task<IActionResult> AlterarSenha()
        {
            var user = await _context.Users
                .FirstOrDefaultAsync(user => user.idUser == Guid.Parse(User.FindFirstValue("idUser")));

            return View("AlterarSenha", user);
        }

        [HttpPost]
        public async Task<IActionResult> AlterarSenha(string previousPassword, string newPassword1, string newPassword2)
        {
            var user = await _context.Users
                .FirstOrDefaultAsync(user => user.idUser == Guid.Parse(User.FindFirstValue("idUser")));

            if (user != null)
            {
                if (string.IsNullOrEmpty(previousPassword))
                {
                    ViewBag.Message = "Senha atual vazia.";
                }
                else
                {
                    bool ispasswordOk = BCrypt.Net.BCrypt.Verify(previousPassword, user.password);
                    if (ispasswordOk)
                    {
                        if (!string.IsNullOrEmpty(newPassword1) && !string.IsNullOrEmpty(newPassword2) && newPassword1 == newPassword2 && newPassword1.Length >= 8)
                        {
                            user.password = BCrypt.Net.BCrypt.HashPassword(newPassword1);
                            await _context.SaveChangesAsync();
                            TempData["success"] = "Sua Senha foi alterada com sucesso!";                       
                            return View();
                        }
                        else
                        {
                            ViewBag.Message = "Confirmação de senha inválida";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "Senha atual errada.";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> DeleteUser()
        {
            var user = _context.Users.First(excluir => excluir.idUser == Guid.Parse(User.FindFirstValue("idUser")));
            _context.Users.Remove(user);
            _context.SaveChanges();
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }


        public IActionResult RecuperarSenha()
        { 
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RecuperarSenha(ForgotPassword model)
        {
            if (ModelState.IsValid)
            {
                var emailExists = _context.Users.FirstOrDefault(o => o.email == model.email);
                if (emailExists != null)
                {
                    try
                    {
                        DotNetEnv.Env.Load();
                        model.idForgotPass = Guid.NewGuid();
                        model.emailSent = true;
                        model.email = emailExists.email;
                        model.passwordResetToken = Guid.NewGuid();
                        model.created_date = DateTime.Now;
                        _context.Add(model);
                        _context.SaveChanges();

                        string apiKey = Environment.GetEnvironmentVariable("API_KEY");
                        var client = new SendGridClient(apiKey);

                        var from = new EmailAddress("study2gether7789@gmail.com", "Study2Gether");

src/Study2gether/Study2gether/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Study2gether</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Study2gether</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Leave Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminUsers" asp-action="Index">User List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminPost" asp-action="Index">Post List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminAnswers" asp-action="Index">Answers List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminAxis" asp-action="Index">Axis List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminMicrofoundations" asp-action="Index">Microfoundations List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index">Categories List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminReactions" asp-action="Index">Reactions List</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <p>Oi, @User.Identity.Name</p>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Sair</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Cadastro">Cadastro</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Study2gether - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>